services:
  - type: web
    name: jkm-edit-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && mkdir -p uploads outputs
    startCommand: "gunicorn app:app"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
